#!/bin/bash

# Description of muon IDs:
# (***) muon-qa_id30619: GeometryAlignedFix10Fix15ShiftCh1BNew2 (bottom only shift)
# (***) muon-qa_id31157: GeometryAlignedFix10Fix15Shift04Ch1BNew2: bottom only CH1 shift with half the amount
# muon-qa_id30620: GeometryAlignedFix10Fix15ShiftCh1TBNew2 (top and bottom half shift)
# muon-qa_id30697: GeometryAligned (reference)
# muon-qa_id30991: GeometryAlignedShiftY (global shift Y)
# (***) muon-qa_id30992: GeometryAlignedFix110Fix15New2T5 (better javier new2)
# (***) muon-qa_id30993: GeometryAlignedFix110Fix15New2T5ShiftY (better javier new2 + shift)
# (***) muon-qa OR muon-qa_id32007 (for newer versions): GeometryAlignedFix110Fix19NewIST7
# (***) muon-qa_id32943: GeometryAlignedFix110Fix19alnNewadSU1
# (***) muon-qa_id34687: GeometryAlignedLHC24adap3maFix110Shift10OP1

# Generic shows top-bottom/left-right in the 'normal' subdivisions (TT, TB, BB, etc.)
# Specific shows a more in-depth study of the TB and LR positive and negative muons

##### LHC24an_pass1_skimmed #####
# top-bottom
# --- generic
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_GeometryAlignedFix10Fix15ShiftCh1BNew2", "top-bottom", "draw_generic", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30619/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_GeometryAlignedFix10Fix15Shift04Ch1BNew2", "top-bottom", "draw_generic", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id31157/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_GeometryAlignedFix110Fix15New2T5", "top-bottom", "draw_generic", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30992/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_GeometryAlignedFix110Fix15New2T5ShiftY", "top-bottom", "draw_generic", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30993/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_GeometryAlignedFix110Fix19NewIST7", "top-bottom", "draw_generic", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_GeometryAlignedFix110Fix19alnNewadSU1", "top-bottom", "draw_generic", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_GeometryAlignedFix110Fix19alnNewadSU1_Hyperloop_22_07_2025.root", "muon-qa_id32943/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'

# # --- specific
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_GeometryAlignedFix10Fix15ShiftCh1BNew2", "top-bottom", "draw_specific", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30619/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_GeometryAlignedFix10Fix15Shift04Ch1BNew2", "top-bottom", "draw_specific", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id31157/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_GeometryAlignedFix110Fix15New2T5", "top-bottom", "draw_specific", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30992/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_GeometryAlignedFix110Fix15New2T5ShiftY", "top-bottom", "draw_specific", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30993/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_GeometryAlignedFix110Fix19NewIST7", "top-bottom", "draw_specific", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_GeometryAlignedFix110Fix19alnNewadSU1", "top-bottom", "draw_specific", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_GeometryAlignedFix110Fix19alnNewadSU1_Hyperloop_22_07_2025.root", "muon-qa_id32943/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'

# # left-right
# # --- generic
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_GeometryAlignedFix10Fix15ShiftCh1BNew2", "left-right", "draw_generic", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30619/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_GeometryAlignedFix10Fix15Shift04Ch1BNew2", "left-right", "draw_generic", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id31157/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_GeometryAlignedFix110Fix15New2T5", "left-right", "draw_generic", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30992/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_GeometryAlignedFix110Fix15New2T5ShiftY", "left-right", "draw_generic", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30993/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_GeometryAlignedFix110Fix19NewIST7", "left-right", "draw_generic", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_GeometryAlignedFix110Fix19alnNewadSU1", "left-right", "draw_generic", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_GeometryAlignedFix110Fix19alnNewadSU1_Hyperloop_22_07_2025.root", "muon-qa_id32943/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'

# --- specific
#root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_GeometryAlignedFix10Fix15ShiftCh1BNew2", "left-right", "draw_specific", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30619/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
#root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_GeometryAlignedFix10Fix15Shift04Ch1BNew2", "left-right", "draw_specific", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id31157/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
#root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_GeometryAlignedFix110Fix15New2T5", "left-right", "draw_specific", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30992/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
#root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_GeometryAlignedFix110Fix15New2T5ShiftY", "left-right", "draw_specific", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30993/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
#root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_GeometryAlignedFix110Fix19NewIST7", "left-right", "draw_specific", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'

##### LHC24an_pass1_skimmed #####
# top-bottom
# --- generic
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_small_GeometryAlignedLHC24adap3maFix110Shift10OP1", "top-bottom", "draw_generic", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_small_Hyperloop_09_08_2025.root", "muon-qa_id34687/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'

# # --- specific
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_small_GeometryAlignedLHC24adap3maFix110Shift10OP1", "top-bottom", "draw_specific", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_small_Hyperloop_09_08_2025.root", "muon-qa_id34687/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'

# # left-right
# # --- generic
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_small_GeometryAlignedLHC24adap3maFix110Shift10OP1", "left-right", "draw_generic", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_small_Hyperloop_09_08_2025.root", "muon-qa_id34687/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'

# --- specific
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_small_GeometryAlignedLHC24adap3maFix110Shift10OP1", "left-right", "draw_specific", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24an_pass1_skimmed_small_Hyperloop_09_08_2025.root", "muon-qa_id34687/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'

##### LHC24am_pass1_skimmed #####
# top-bottom
# --- generic
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24am_GeometryAlignedFix10Fix15ShiftCh1BNew2", "top-bottom", "draw_generic", "AnalysisResults-muonQA_LHC24am_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24am_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30619/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24am_GeometryAlignedFix10Fix15Shift04Ch1BNew2", "top-bottom", "draw_generic", "AnalysisResults-muonQA_LHC24am_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24am_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id31157/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24am_GeometryAlignedFix110Fix15New2T5", "top-bottom", "draw_generic", "AnalysisResults-muonQA_LHC24am_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24am_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30992/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24am_GeometryAlignedFix110Fix15New2T5ShiftY", "top-bottom", "draw_generic", "AnalysisResults-muonQA_LHC24am_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24am_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30993/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24am_GeometryAlignedFix110Fix19NewIST7", "top-bottom", "draw_generic", "AnalysisResults-muonQA_LHC24am_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24am_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'

# # --- specific
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24am_GeometryAlignedFix10Fix15ShiftCh1BNew2", "top-bottom", "draw_specific", "AnalysisResults-muonQA_LHC24am_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24am_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30619/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24am_GeometryAlignedFix10Fix15Shift04Ch1BNew2", "top-bottom", "draw_specific", "AnalysisResults-muonQA_LHC24am_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24am_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id31157/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24am_GeometryAlignedFix110Fix15New2T5", "top-bottom", "draw_specific", "AnalysisResults-muonQA_LHC24am_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24am_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30992/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24am_GeometryAlignedFix110Fix15New2T5ShiftY", "top-bottom", "draw_specific", "AnalysisResults-muonQA_LHC24am_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24am_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30993/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24am_GeometryAlignedFix110Fix19NewIST7", "top-bottom", "draw_specific", "AnalysisResults-muonQA_LHC24am_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24am_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'

# # left-right
# # --- generic
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24am_GeometryAlignedFix10Fix15ShiftCh1BNew2", "left-right", "draw_generic", "AnalysisResults-muonQA_LHC24am_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24am_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30619/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24am_GeometryAlignedFix10Fix15Shift04Ch1BNew2", "left-right", "draw_generic", "AnalysisResults-muonQA_LHC24am_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24am_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id31157/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24am_GeometryAlignedFix110Fix15New2T5", "left-right", "draw_generic", "AnalysisResults-muonQA_LHC24am_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24am_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30992/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24am_GeometryAlignedFix110Fix15New2T5ShiftY", "left-right", "draw_generic", "AnalysisResults-muonQA_LHC24am_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24am_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30993/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24am_GeometryAlignedFix110Fix19NewIST7", "left-right", "draw_generic", "AnalysisResults-muonQA_LHC24am_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24am_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'

# --- specific
#root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24am_GeometryAlignedFix10Fix15ShiftCh1BNew2", "left-right", "draw_specific", "AnalysisResults-muonQA_LHC24am_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24am_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30619/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
#root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24am_GeometryAlignedFix10Fix15Shift04Ch1BNew2", "left-right", "draw_specific", "AnalysisResults-muonQA_LHC24am_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24am_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id31157/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
#root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24am_GeometryAlignedFix110Fix15New2T5", "left-right", "draw_specific", "AnalysisResults-muonQA_LHC24am_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24am_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30992/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
#root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24am_GeometryAlignedFix110Fix15New2T5ShiftY", "left-right", "draw_specific", "AnalysisResults-muonQA_LHC24am_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24am_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30993/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
#root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24am_GeometryAlignedFix110Fix19NewIST7", "left-right", "draw_specific", "AnalysisResults-muonQA_LHC24am_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24am_pass1_skimmed_all_geometries_Hyperloop_11_07_2025.root", "muon-qa/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'

##### LHC24al_pass1_skimmed #####
# (same polarity as `am`, but more statistics)
# top-bottom
# --- generic
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24al_GeometryAlignedFix10Fix15ShiftCh1BNew2", "top-bottom", "draw_generic", "AnalysisResults-muonQA_LHC24al_pass1_skimmed_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24al_pass1_skimmed_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30619/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24al_GeometryAlignedFix10Fix15Shift04Ch1BNew2", "top-bottom", "draw_generic", "AnalysisResults-muonQA_LHC24al_pass1_skimmed_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24al_pass1_skimmed_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id31157/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24al_GeometryAlignedFix110Fix15New2T5", "top-bottom", "draw_generic", "AnalysisResults-muonQA_LHC24al_pass1_skimmed_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24al_pass1_skimmed_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30992/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24al_GeometryAlignedFix110Fix15New2T5ShiftY", "top-bottom", "draw_generic", "AnalysisResults-muonQA_LHC24al_pass1_skimmed_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24al_pass1_skimmed_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30993/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24al_GeometryAlignedFix110Fix19NewIST7", "top-bottom", "draw_generic", "AnalysisResults-muonQA_LHC24al_pass1_skimmed_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24al_pass1_skimmed_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id32007/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24al_GeometryAlignedFix110Fix19alnNewadSU1", "top-bottom", "draw_generic", "AnalysisResults-muonQA_LHC24al_pass1_skimmed_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24al_pass1_skimmed_GeometryAlignedFix110Fix19alnNewadSU1_Hyperloop_18_07_2025.root", "muon-qa_id32943/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'

# # --- specific
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24al_GeometryAlignedFix10Fix15ShiftCh1BNew2", "top-bottom", "draw_specific", "AnalysisResults-muonQA_LHC24al_pass1_skimmed_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24al_pass1_skimmed_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30619/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24al_GeometryAlignedFix10Fix15Shift04Ch1BNew2", "top-bottom", "draw_specific", "AnalysisResults-muonQA_LHC24al_pass1_skimmed_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24al_pass1_skimmed_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id31157/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24al_GeometryAlignedFix110Fix15New2T5", "top-bottom", "draw_specific", "AnalysisResults-muonQA_LHC24al_pass1_skimmed_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24al_pass1_skimmed_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30992/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24al_GeometryAlignedFix110Fix15New2T5ShiftY", "top-bottom", "draw_specific", "AnalysisResults-muonQA_LHC24al_pass1_skimmed_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24al_pass1_skimmed_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30993/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24al_GeometryAlignedFix110Fix19NewIST7", "top-bottom", "draw_specific", "AnalysisResults-muonQA_LHC24al_pass1_skimmed_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24al_pass1_skimmed_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id32007/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24al_GeometryAlignedFix110Fix19alnNewadSU1", "top-bottom", "draw_specific", "AnalysisResults-muonQA_LHC24al_pass1_skimmed_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24al_pass1_skimmed_GeometryAlignedFix110Fix19alnNewadSU1_Hyperloop_18_07_2025.root", "muon-qa_id32943/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'

# # left-right
# # --- generic
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24al_GeometryAlignedFix10Fix15ShiftCh1BNew2", "left-right", "draw_generic", "AnalysisResults-muonQA_LHC24al_pass1_skimmed_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24al_pass1_skimmed_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30619/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24al_GeometryAlignedFix10Fix15Shift04Ch1BNew2", "left-right", "draw_generic", "AnalysisResults-muonQA_LHC24al_pass1_skimmed_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24al_pass1_skimmed_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id31157/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24al_GeometryAlignedFix110Fix15New2T5", "left-right", "draw_generic", "AnalysisResults-muonQA_LHC24al_pass1_skimmed_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24al_pass1_skimmed_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30992/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24al_GeometryAlignedFix110Fix15New2T5ShiftY", "left-right", "draw_generic", "AnalysisResults-muonQA_LHC24al_pass1_skimmed_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24al_pass1_skimmed_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30993/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24al_GeometryAlignedFix110Fix19NewIST7", "left-right", "draw_generic", "AnalysisResults-muonQA_LHC24al_pass1_skimmed_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24al_pass1_skimmed_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id32007/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24al_GeometryAlignedFix110Fix19alnNewadSU1", "left-right", "draw_generic", "AnalysisResults-muonQA_LHC24al_pass1_skimmed_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_LHC24al_pass1_skimmed_GeometryAlignedFix110Fix19alnNewadSU1_Hyperloop_18_07_2025.root", "muon-qa_id32943/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'


##### merged LHC24an_LHC24am_pass1_skimmed #####
# top-bottom
# --- generic
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_LHC24am_GeometryAlignedFix10Fix15ShiftCh1BNew2", "top-bottom", "draw_generic", "AnalysisResults-muonQA_merged_LHC24an_LHC24am_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_merged_LHC24an_LHC24am_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30619/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_LHC24am_GeometryAlignedFix10Fix15Shift04Ch1BNew2", "top-bottom", "draw_generic", "AnalysisResults-muonQA_merged_LHC24an_LHC24am_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_merged_LHC24an_LHC24am_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id31157/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_LHC24am_GeometryAlignedFix110Fix15New2T5", "top-bottom", "draw_generic", "AnalysisResults-muonQA_merged_LHC24an_LHC24am_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_merged_LHC24an_LHC24am_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30992/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_LHC24am_GeometryAlignedFix110Fix15New2T5ShiftY", "top-bottom", "draw_generic", "AnalysisResults-muonQA_merged_LHC24an_LHC24am_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_merged_LHC24an_LHC24am_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30993/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_LHC24am_GeometryAlignedFix110Fix19NewIST7", "top-bottom", "draw_generic", "AnalysisResults-muonQA_merged_LHC24an_LHC24am_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_merged_LHC24an_LHC24am_all_geometries_Hyperloop_11_07_2025.root", "muon-qa/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'

# # --- specific
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_LHC24am_GeometryAlignedFix10Fix15ShiftCh1BNew2", "top-bottom", "draw_specific", "AnalysisResults-muonQA_merged_LHC24an_LHC24am_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_merged_LHC24an_LHC24am_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30619/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_LHC24am_GeometryAlignedFix10Fix15Shift04Ch1BNew2", "top-bottom", "draw_specific", "AnalysisResults-muonQA_merged_LHC24an_LHC24am_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_merged_LHC24an_LHC24am_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id31157/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_LHC24am_GeometryAlignedFix110Fix15New2T5", "top-bottom", "draw_specific", "AnalysisResults-muonQA_merged_LHC24an_LHC24am_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_merged_LHC24an_LHC24am_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30992/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_LHC24am_GeometryAlignedFix110Fix15New2T5ShiftY", "top-bottom", "draw_specific", "AnalysisResults-muonQA_merged_LHC24an_LHC24am_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_merged_LHC24an_LHC24am_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30993/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_LHC24am_GeometryAlignedFix110Fix19NewIST7", "top-bottom", "draw_specific", "AnalysisResults-muonQA_merged_LHC24an_LHC24am_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_merged_LHC24an_LHC24am_all_geometries_Hyperloop_11_07_2025.root", "muon-qa/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'

# # left-right
# # --- generic
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_LHC24am_GeometryAlignedFix10Fix15ShiftCh1BNew2", "left-right", "draw_generic", "AnalysisResults-muonQA_merged_LHC24an_LHC24am_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_merged_LHC24an_LHC24am_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30619/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_LHC24am_GeometryAlignedFix10Fix15Shift04Ch1BNew2", "left-right", "draw_generic", "AnalysisResults-muonQA_merged_LHC24an_LHC24am_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_merged_LHC24an_LHC24am_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id31157/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_LHC24am_GeometryAlignedFix110Fix15New2T5", "left-right", "draw_generic", "AnalysisResults-muonQA_merged_LHC24an_LHC24am_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_merged_LHC24an_LHC24am_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30992/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_LHC24am_GeometryAlignedFix110Fix15New2T5ShiftY", "left-right", "draw_generic", "AnalysisResults-muonQA_merged_LHC24an_LHC24am_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_merged_LHC24an_LHC24am_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30993/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_LHC24am_GeometryAlignedFix110Fix19NewIST7", "left-right", "draw_generic", "AnalysisResults-muonQA_merged_LHC24an_LHC24am_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_merged_LHC24an_LHC24am_all_geometries_Hyperloop_11_07_2025.root", "muon-qa/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'

# --- specific
#root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_LHC24am_GeometryAlignedFix10Fix15ShiftCh1BNew2", "left-right", "draw_specific", "AnalysisResults-muonQA_merged_LHC24an_LHC24am_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_merged_LHC24an_LHC24am_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30619/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
#root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_LHC24am_GeometryAlignedFix10Fix15Shift04Ch1BNew2", "left-right", "draw_specific", "AnalysisResults-muonQA_merged_LHC24an_LHC24am_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_merged_LHC24an_LHC24am_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id31157/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
#root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_LHC24am_GeometryAlignedFix110Fix15New2T5", "left-right", "draw_specific", "AnalysisResults-muonQA_merged_LHC24an_LHC24am_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_merged_LHC24an_LHC24am_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30992/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
#root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_LHC24am_GeometryAlignedFix110Fix15New2T5ShiftY", "left-right", "draw_specific", "AnalysisResults-muonQA_merged_LHC24an_LHC24am_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_merged_LHC24an_LHC24am_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30993/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
#root -l -q -b 'DiMuonMassSpectrum-muonQA.C("LHC24an_LHC24am_GeometryAlignedFix110Fix19NewIST7", "left-right", "draw_specific", "AnalysisResults-muonQA_merged_LHC24an_LHC24am_all_geometries_Hyperloop_11_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_merged_LHC24an_LHC24am_all_geometries_Hyperloop_11_07_2025.root", "muon-qa/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'

##### merged LHC24an_LHC24al_pass1_skimmed #####
# top-bottom
# --- generic
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("merged_LHC24an_LHC24al_GeometryAlignedFix10Fix15ShiftCh1BNew2", "top-bottom", "draw_generic", "AnalysisResults-muonQA_merged_LHC24an_LHC24al_pass1_merged_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_merged_LHC24an_LHC24al_pass1_merged_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30619/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("merged_LHC24an_LHC24al_GeometryAlignedFix10Fix15Shift04Ch1BNew2", "top-bottom", "draw_generic", "AnalysisResults-muonQA_merged_LHC24an_LHC24al_pass1_merged_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_merged_LHC24an_LHC24al_pass1_merged_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id31157/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("merged_LHC24an_LHC24al_GeometryAlignedFix110Fix15New2T5", "top-bottom", "draw_generic", "AnalysisResults-muonQA_merged_LHC24an_LHC24al_pass1_merged_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_merged_LHC24an_LHC24al_pass1_merged_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30992/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("merged_LHC24an_LHC24al_GeometryAlignedFix110Fix15New2T5ShiftY", "top-bottom", "draw_generic", "AnalysisResults-muonQA_merged_LHC24an_LHC24al_pass1_merged_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_merged_LHC24an_LHC24al_pass1_merged_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30993/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# # root -l -q -b 'DiMuonMassSpectrum-muonQA.C("merged_LHC24an_LHC24al_GeometryAlignedFix110Fix19NewIST7", "top-bottom", "draw_generic", "AnalysisResults-muonQA_merged_LHC24an_LHC24al_pass1_merged_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_merged_LHC24an_LHC24al_pass1_merged_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id32007/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("merged_LHC24anLHC24al_GeometryAlignedFix110Fix19alnNewadSU1", "top-bottom", "draw_generic", "AnalysisResults-muonQA_merged_LHC24an_LHC24al_pass1_merged_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_merged_LHC24an_LHC24al_pass1_merged_all_geometries_Hyperloop_22_07_2025.root", "muon-qa_id32943/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'

# # --- specific
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("merged_LHC24an_LHC24al_GeometryAlignedFix10Fix15ShiftCh1BNew2", "top-bottom", "draw_specific", "AnalysisResults-muonQA_merged_LHC24an_LHC24al_pass1_merged_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_merged_LHC24an_LHC24al_pass1_merged_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30619/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("merged_LHC24an_LHC24al_GeometryAlignedFix10Fix15Shift04Ch1BNew2", "top-bottom", "draw_specific", "AnalysisResults-muonQA_merged_LHC24an_LHC24al_pass1_merged_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_merged_LHC24an_LHC24al_pass1_merged_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id31157/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("merged_LHC24an_LHC24al_GeometryAlignedFix110Fix15New2T5", "top-bottom", "draw_specific", "AnalysisResults-muonQA_merged_LHC24an_LHC24al_pass1_merged_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_merged_LHC24an_LHC24al_pass1_merged_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30992/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("merged_LHC24an_LHC24al_GeometryAlignedFix110Fix15New2T5ShiftY", "top-bottom", "draw_specific", "AnalysisResults-muonQA_merged_LHC24an_LHC24al_pass1_merged_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_merged_LHC24an_LHC24al_pass1_merged_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30993/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# # root -l -q -b 'DiMuonMassSpectrum-muonQA.C("merged_LHC24an_LHC24al_GeometryAlignedFix110Fix19NewIST7", "top-bottom", "draw_specific", "AnalysisResults-muonQA_merged_LHC24an_LHC24al_pass1_merged_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_merged_LHC24an_LHC24al_pass1_merged_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id32007/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("merged_LHC24anLHC24al_GeometryAlignedFix110Fix19alnNewadSU1", "top-bottom", "draw_specific", "AnalysisResults-muonQA_merged_LHC24an_LHC24al_pass1_merged_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_merged_LHC24an_LHC24al_pass1_merged_all_geometries_Hyperloop_22_07_2025.root", "muon-qa_id32943/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'

# # left-right
# # --- generic
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("merged_LHC24an_LHC24al_GeometryAlignedFix10Fix15ShiftCh1BNew2", "left-right", "draw_generic", "AnalysisResults-muonQA_merged_LHC24an_LHC24al_pass1_merged_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_merged_LHC24an_LHC24al_pass1_merged_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30619/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("merged_LHC24an_LHC24al_GeometryAlignedFix10Fix15Shift04Ch1BNew2", "left-right", "draw_generic", "AnalysisResults-muonQA_merged_LHC24an_LHC24al_pass1_merged_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_merged_LHC24an_LHC24al_pass1_merged_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id31157/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("merged_LHC24an_LHC24al_GeometryAlignedFix110Fix15New2T5", "left-right", "draw_generic", "AnalysisResults-muonQA_merged_LHC24an_LHC24al_pass1_merged_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_merged_LHC24an_LHC24al_pass1_merged_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30992/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("merged_LHC24an_LHC24al_GeometryAlignedFix110Fix15New2T5ShiftY", "left-right", "draw_generic", "AnalysisResults-muonQA_merged_LHC24an_LHC24al_pass1_merged_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_merged_LHC24an_LHC24al_pass1_merged_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30993/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# # root -l -q -b 'DiMuonMassSpectrum-muonQA.C("merged_LHC24an_LHC24al_GeometryAlignedFix110Fix19NewIST7", "left-right", "draw_generic", "AnalysisResults-muonQA_merged_LHC24an_LHC24al_pass1_merged_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_merged_LHC24an_LHC24al_pass1_merged_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id32007/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'
# root -l -q -b 'DiMuonMassSpectrum-muonQA.C("merged_LHC24anLHC24al_GeometryAlignedFix110Fix19alnNewadSU1", "left-right", "draw_generic", "AnalysisResults-muonQA_merged_LHC24an_LHC24al_pass1_merged_all_geometries_Hyperloop_15_07_2025.root", "muon-qa_id30697/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts", "AnalysisResults-muonQA_merged_LHC24an_LHC24al_pass1_merged_all_geometries_Hyperloop_22_07_2025.root", "muon-qa_id32943/dimuon/same-event/invariantMass_pT_MuonKine_MuonCuts")'